export const CLIENTS_DOWNLOAD_ALL_FROM_SERVER = 'CLIENTS_DOWNLOAD_ALL_FROM_SERVER';
export const CLIENTS_WRITE_DATA_TO_VUEX = 'CLIENTS_WRITE_DATA_TO_VUEX';
export const CLIENTS_GET_BY_INN = 'CLIENTS_GET_BY_INN';
export const CLIENTS_GET_ALL = 'CLIENTS_GET_ALL';
export const CLIENTS_IS_LOADED = 'CLIENTS_IS_LOADED';
export const CLIENTS_UPLOAD_TO_SERVER = 'CLIENTS_UPLOAD_TO_SERVER';

