export const GOODS_DOWNLOAD_ALL_FROM_SERVER = 'GOODS_DOWNLOAD_ALL_FROM_SERVER';
export const GOODS_UPLOAD_ALL_TO_SERVER = 'GOODS_UPLOAD_ALL_TO_SERVER';
export const GOODS_GET_ALL = 'GOODS_GET_ALL';
export const GOODS_GET_BY_ITEM = 'GOODS_GET_BY_ITEM';
export const GOODS_WRITE_ALL_TO_VUEX = 'GOODS_WRITE_ALL_TO_VUEX';