export const MANAGERS_DOWNLOAD_ALL_FROM_SERVER = 'MANAGERS_DOWNLOAD_ALL_FROM_SERVER';
export const MANAGERS_GET_ALL = 'MANAGERS_GET_ALL';
export const MANAGERS_GET_BY_ID = 'MANAGERS_GET_BY_ID';
export const MANAGERS_WRITE_ALL_TO_VUEX = 'MANAGERS_WRITE_ALL_TO_VUEX';
export const MANAGERS_ERROR = 'MANAGERS_ERROR';
