export const PRICES_REQUEST = 'PRICES_REQUEST';
export const PRICES_SUCCESS = 'PRICES_SUCCESS';
export const PRICES_LOADING = 'PRICES_LOADING';
export const PRICES_ERROR = 'PRICES_ERROR';
export const PRICES_GET_ALL = 'PRICES_GET_ALL';
export const PRICES_WRITE_ALL_TOVUEX = 'PRICES_WRITE_ALL_TOVUEX';
